version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quarkus_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolistdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  #  volumes:
  #    - db_data:/var/lib/mysql
  #  networks:
  #    - quarkus_network

#  quarkus:
#    image: to-do-list
#    container_name: myqrksapp
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    environment:
#      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/todolistdb
#      QUARKUS_DATASOURCE_USERNAME: user
#      QUARKUS_DATASOURCE_PASSWORD: password
#    depends_on:
#      - db
#    networks:
#      - quarkus_network
#
#volumes:
#  db_data:
#
#networks:
#  quarkus_network:
