version: '2.27'

services:
  vuejs-app:
    image: node:18-alpine
    container_name: vuejs-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run serve
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true